;
; File generated by cc65 v 2.18 - Debian 2.19-2
;
	.fopt		compiler,"cc65 v 2.18 - Debian 2.19-2"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_zsm_init
	.export		_zsm_tick
	.export		_zsm_stop
	.export		_zsm_restart
	.export		_main

.segment	"BSS"

_zsm_ptr_lo:
	.res	1,$00
_zsm_ptr_hi:
	.res	1,$00
_loop_ptr_lo:
	.res	1,$00
_loop_ptr_hi:
	.res	1,$00
_tick_count:
	.res	1,$00
_tick_target:
	.res	1,$00
_tempo:
	.res	1,$00
_flags:
	.res	1,$00
_ch_mask:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ read_byte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_byte: near

.segment	"CODE"

	lda     _zsm_ptr_lo
	sta     ptr1
	lda     _zsm_ptr_hi
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	inc     _zsm_ptr_lo
	bne     L0005
	inc     _zsm_ptr_hi
L0005:	ldx     #$00
	lda     (sp,x)
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ zsm_init (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_zsm_init: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp5
	ldy     #$05
	lda     (sp),y
	sta     _zsm_ptr_lo
	iny
	lda     (sp),y
	sta     _zsm_ptr_hi
	jsr     _read_byte
	ldy     #$04
	sta     (sp),y
	jsr     _read_byte
	ldy     #$03
	sta     (sp),y
	jsr     _read_byte
	ldy     #$02
	sta     (sp),y
	ldy     #$04
	lda     (sp),y
	cmp     #$5A
	bne     L0081
	dey
	lda     (sp),y
	cmp     #$53
	bne     L0081
	dey
	lda     (sp),y
	cmp     #$4D
	beq     L0015
L0081:	lda     #$00
	jmp     L0080
L0015:	jsr     _read_byte
	jsr     _read_byte
	sta     _loop_ptr_lo
	jsr     _read_byte
	sta     _loop_ptr_hi
	jsr     _read_byte
	jsr     _read_byte
	lda     #$00
	sta     _tick_count
	lda     #$01
	sta     _tick_target
	sta     _tempo
	lda     #$FF
	sta     _ch_mask
	ldy     #$00
	tya
	sta     (sp),y
	iny
	sta     (sp),y
L0029:	ldy     #$01
	lda     (sp),y
	cmp     #$00
	bne     L0030
	dey
	lda     (sp),y
	cmp     #$40
L0030:	bcs     L002A
	lda     #$00
	tay
	clc
	adc     (sp),y
	sta     ptr1
	lda     #$03
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	tax
	lda     #$01
	jsr     addeq0sp
	jmp     L0029
L002A:	lda     #$01
L0080:	sta     _flags
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ process_cmd (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_process_cmd: near

.segment	"CODE"

	jsr     _read_byte
	jsr     pusha
	ldy     #$00
	lda     (sp),y
	and     #$80
	beq     L0084
	lda     (sp),y
	and     #$7F
	jsr     pusha
	jsr     _read_byte
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	sta     $D100
	lda     #$00
	sta     $D101
	sta     $D102
	dey
	lda     (sp),y
	sta     $D103
	jsr     incsp2
	jmp     incsp1
L0084:	lda     (sp),y
	bne     L0089
	lda     _loop_ptr_lo
	bne     L0085
	lda     _loop_ptr_hi
	beq     L0087
L0085:	lda     _loop_ptr_lo
	sta     _zsm_ptr_lo
	lda     _loop_ptr_hi
	sta     _zsm_ptr_hi
	lda     #$01
	jmp     L008B
L0087:	sta     _flags
	jmp     incsp1
L0089:	lda     (sp),y
L008B:	sta     _tick_target
	sty     _tick_count
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ zsm_tick (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_zsm_tick: near

.segment	"CODE"

	lda     _flags
	and     #$01
	beq     L0062
	inc     _tick_count
	jmp     L008C
L0061:	jsr     _process_cmd
	lda     _flags
	and     #$01
	beq     L0062
L008C:	lda     _tick_count
	cmp     _tick_target
	bcs     L0061
L0062:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ zsm_stop (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_zsm_stop: near

.segment	"CODE"

	lda     #$00
	sta     _flags
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ zsm_restart (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_zsm_restart: near

.segment	"CODE"

	lda     _zsm_ptr_lo
	sec
	sbc     #$08
	sta     _zsm_ptr_lo
	lda     _zsm_ptr_lo
	beq     L008E
	dec     _zsm_ptr_hi
	lda     #$00
L008E:	sta     _tick_count
	lda     #$01
	sta     _tick_target
	sta     _flags
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$20
	lda     #$00
	jsr     _zsm_init
	jmp     L007D
L007B:	jsr     _zsm_tick
L007D:	lda     _flags
	and     #$01
	bne     L007B
	rts

.endproc

