/* logo.x16.h — generated by vera_logo_editor.py */
/* VeraX16 80×30 logo — VERA-native bounding-box table.    */
#ifndef LOGO_X16_H
#define LOGO_X16_H

#define LOGO_COLS      80
#define LOGO_ROWS      30
#define LOGO_START_ROW 0
#define LOGO_START_COL 0
#define LOGO_NUM_ROWS  7
#define LOGO_NUM_COLS  7

/*
 * logo_data[]: header (4B) + body (num_rows*num_cols*2B), row-major.
 *   [0] start_row  [1] start_col  [2] num_rows  [3] num_cols
 *   [4..] vera_color, glyph  per cell  (vera_color=(bg<<4)|fg)
 *
 * ALL cells inside the bounding box are included — touching or not —
 * so custom background colors inside the logo area are preserved.
 *
 * In runcpm.c:  draw_logo(vctl);
 */
static const unsigned char logo_data[] = {
    /* header */ 0x00,0x00,0x07,0x07,
    0x64,0x0A,0x61,0x20,0x61,0x20,0x61,0x20,0x61,0x20,0x61,0x20,0x64,0x08,0xE6,0x16,
    0x6E,0x0A,0x61,0x20,0x61,0x20,0x61,0x20,0x6E,0x08,0xE6,0x02,0x36,0x19,0x36,0x20,
    0x63,0x0A,0x61,0x20,0x63,0x08,0x36,0x20,0x63,0x19,0x61,0x20,0x65,0x0D,0x56,0x0F,
    0x61,0x20,0x56,0x09,0x65,0x0D,0x61,0x20,0x61,0x20,0x67,0x0E,0x76,0x0C,0x61,0x20,
    0x76,0x0B,0x67,0x0E,0x61,0x20,0x68,0x02,0x86,0x20,0x86,0x08,0x61,0x20,0x86,0x0A,
    0x86,0x20,0x68,0x16,0x26,0x19,0x26,0x08,0x61,0x20,0x61,0x20,0x61,0x20,0x26,0x0A,
    0x62,0x19,
};

/*
 * draw_logo() — render logo directly via VERA VCTL block.
 * Positions cursor once per row; CURSOR_X auto-advances each putchar.
 * ROWCRS_OS/COLCRS_OS kept in sync to prevent VBI cursor_tick override.
 * v = vctl pointer (pass NULL to skip VERA writes, e.g. no driver).
 */
static void draw_logo(volatile unsigned char *v)
{
    const unsigned char *p = logo_data;
    unsigned char sr = *p++; /* start_row */
    unsigned char sc = *p++; /* start_col */
    unsigned char nr = *p++; /* num_rows  */
    unsigned char nc = *p++; /* num_cols  */
    unsigned char r, c;
    for (r = sr; r < (unsigned char)(sr + nr); ++r) {
        if (v) {
            v[9] = r;   /* VCTL_CURSOR_Y */
            v[8] = sc;  /* VCTL_CURSOR_X */
            *((volatile unsigned char*)0x0054) = r;  /* ROWCRS_OS */
            *((volatile unsigned char*)0x0055) = sc; /* COLCRS_OS */
        }
        for (c = sc; c < (unsigned char)(sc + nc); ++c) {
            if (v) v[7] = *p++; /* VCTL_PARAM1: vera_color */
            else   p++;
            putchar(*p++);      /* glyph — CURSOR_X auto-advances */
        }
    }
}

#endif /* LOGO_X16_H */
